name: QA Automation Pipeline

on:
push:
branches:
- master
- main

jobs:
ui-tests:

```
runs-on: ubuntu-latest

defaults:
  run:
    working-directory: ui-automation

steps:

  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install Dependencies
    run: npm install

  - name: Install Playwright Browsers
    run: npx playwright install --with-deps

  - name: Run Playwright Tests
    run: npx playwright test
```
